### ISSUE TITLE
Error in correctly reading a variable

### ISSUE THREAD

**Issue by Jainil1729** [Capacites/ros_ADS_Beckhoff#1]
Hi!
I was unable to read the variable correctly using this library even after properly establishing the route and making sure that config file is right. The following two issues were found and on whose resolution, I could read the variables correctly:

1. The ADS library version is not up to date with this master: https://github.com/Capacites/ADS.git
2. The variable, m_temp, in Ads_Interface.h is declared as double but is getting improperly cast in the adsReadValue function in Ads_interface.cpp file. I found a workaround by declaring m_temp as uint64_t instead.

Thank you!

**Comment by Capacites** [comment]
Thanks for report !
we update  the ads submodule.

For the second point => 

We know the limitation about unsigned int 64bits value. (I must add in the readme).
To avoid multiple ros message, we choose double to keep float or double value. 
But the limitation you only use 32bits data (uint et int).
Furthermore, we didn't see the utility to use a int64 instead a int32. (check your range of values , maybe you didn't to ?).
If you change m_temp double to  uint64, you will lose the floating part of your floating data in the automate.

You can see in the README list of the variable  type  Support in Beckhoff.

**Comment by Jainil1729** [comment]
Hi, thanks for the fast response.

2. The issue I had with `m_temp` is that I'm trying to retrieve an integer `00000011` which is then put into `double m_temp` as `00000011 00000000 00000000 00000000` but since doubles are using IEEE 754 format, when reading `m_temp`, it turns into `3.76158192263e-37` instead of `3`. Since doubles use 64bits, I changed it into a uint64 for the sake of keeping the same amount of bits and since I don't use doubles I didn't try to read any either.

3. I also found a new issue in the [ADSLib](https://github.com/Capacites/ADS/) used as a submodule in this repo. I'll mention it here but if you want me to add an issue to the ADS repo, I'll do so.
Inside [AdsVariable.h](https://github.com/Capacites/ADS/blob/master/AdsLib/AdsVariable.h) the `AdsVariable` class doesn't properly override the `operator=` defined in the `IAdsVariable` structure.
`IAdsVariable` is declaring `void operator=(const double& value)` while `AdsVariable` is declaring `void operator=(const T& value) const` which means that when we try to write a new value, it calls the empty `IAdsVariable` = operator instead of the proper `AdsVariable` operator.

**Comment by Capacites** [comment]
Please Create an issue on ADSLib.

**Comment by Jainil1729** [comment]
Hi,

How do I raise the issue there? 'Issues' tab seems to be missing from your fork. I think you need to enable it in settings of the fork. If not, then please guide me on any other way.

Thanks!

**Comment by Capacites** [comment]
i resolve the issue ;)
