### ISSUE TITLE
preparation of ADS lib for ROS

### ISSUE THREAD

**Issue by AltinayGrass** [Capacites/ros_ADS_Beckhoff#2]
Hello,

Could you please descript how should we install ADS lib for use like below ?

`add_subdirectory(lib/ADS/AdsLib)`

**Comment by Capacites** [comment]
First do you have clone with recurse module option ?
If you use "catkin_make",  the node, the ads lib is compiled and the message ADS.h is compiled.

**Comment by Capacites** [comment]
I modify the readme for the installation

**Comment by HYD-PG** [comment]
> First do you have clone with recurse module option ? If you use "catkin_make", the node, the ads lib is compiled and the message ADS.h is compiled.
Hi,I would like to ask if I need to download libads.
