### ISSUE TITLE
Class "AdsDevice" has no member "GetDeviceAdsVariables" and Undefined identifier "IAdsVariable"

### ISSUE THREAD

**Issue by HYD-PG** [Capacites/ros_ADS_Beckhoff#4]
Hi,my system is ubuntu22.04,When I use the ADS recommended combination with ROS when migrating it to ROS2, the terminal always reports that Class "AdsDevice" has no member "GetDeviceAdsVariables" and Undefined identifier "IAdsVariable",how to solve it

**Comment by Capacites** [comment]
Currently, we have no plan to translate this node to ROS2. 
Maybe you can fork our deposit and create a branch for ROS2 and push it to our deposit.
 We may be help you to translate our module to ROS 2.
