### ISSUE TITLE
error while loading shared libraries: libads.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HYD-PG** [Capacites/ros_ADS_Beckhoff#5]
Hi,
when i was going to compile and ros run node,the following problem occurred and what is the possible way to solve the issue?
`error while loading shared libraries: libads.so: cannot open shared object file: No such file or directory`

**Comment by Capacites** [comment]
Can you post your CMakelists.txt?? 
check if you have
`add_subdirectory(lib/ADS/AdsLib)
`
in your CMakeLists.txt

**Comment by Capacites** [comment]
@yudonghou123 , 
there the first version for ROS2 = https://github.com/Capacites/ros2_ADS_Beckhoff
It will be tested soon.
